name: Generate Snake

# Este workflow se ejecutará cada 6 horas
on:
  schedule:
    # Cada 6 horas
    - cron: "0 */6 * * *"
  
  # También puedes ejecutarlo manualmente desde las Actions de GitHub
  workflow_dispatch:

# Jobs a ejecutar en el workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Hacer checkout del repositorio
      - name: Checkout the repository
        uses: actions/checkout@v3

    # Paso 2: Crear el directorio 'dist' si no existe
      - name: Crear directorio dist
        run: mkdir -p dist

    # Paso 3: Generar la serpiente de contribuciones
      - name: Generar la serpiente
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MarcoNaredo14  # Cambia por tu nombre de usuario de GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

    # Paso 4: Mostrar el estado del build para depurar
      - run: git status

    # Paso 5: Hacer push de los cambios al branch principal (main o master)
      - name: Push changes to main (or master)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Cambia a 'master' si tu branch principal es master
          force: true

    # Paso 6: Publicar la serpiente en GitHub Pages (branch output)
      - name: Publicar en GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
